services:
  web: &web
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USE_DJANGO_Q: "True"
    image: django_appointment_web_local
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  qcluster:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USE_DJANGO_Q: "True"
    image: django_appointment_qcluster_local
    command: python manage.py qcluster
    depends_on:
      - web
    volumes:
      - .:/app
    env_file:
      - .env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local
