FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
ARG DJANGO_VERSION=5.0.3
RUN pip install --no-cache-dir -r requirements-test.txt Django==${DJANGO_VERSION}

# Make port 8000 available to the world outside this container
EXPOSE 8000

CMD ["python", "manage.py", "test"]
